/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  EDIT_STUFF: 'edit-stuff',
  EDIT_REQUEST: 'edit-request',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  FACULTY_HOME: 'faculty-home',
  ADMIN_HOME: 'admin-home',
  ITSUPPORT_HOME: 'itsupport-home',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  MAP: 'map',
  Room_Avi: 'room',
  FACULTY_SEARCH: 'faculty-search',
  STUDENT_SEARCH: 'student-search',
  FULL_FACULTY_INFO: 'full-faculty-info',
  CLUB_SEARCH: 'club-search',
  PORT_SEARCH: 'port-search',
  PROFILE: 'profile',
  STUDENT_HOME: 'student-home',
  USER_PROFILE: 'user-profile',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  Add_Request: 'add-request',
};
